### ISSUE TITLE
some normals of isosurface incorrect

### ISSUE THREAD

**Issue by chrisjsewell** [chrisjsewell/PyGauss#22]
getting inverse for some areas

**Comment by gabrielelanaro** [comment]
I believe I fixed this but it's not released yet. It'd due to some wierdness with the marching cubes code.

**Comment by chrisjsewell** [comment]
hey, hopefully you got my email about this, but for documentation sake;
my code is in pygauss/isosurface.py in which I've swapped out your marching cubes with the scikit-image implementation (faster but still get the weirdness with having to switching x/y, which could be the route of the problem?)
